title: Al-Cheng's Category
description: Science, Philosophy, Mathematics, and Writings
remote_theme: "jekyll/minima@1e8a445"
header_pages:
  - science.md
  - philosophy.md
  - mathematics.md
  - stories.md
